### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Verdoso** [hazelcast/hazelcast-wm#122]
Hello there,
We have many services unable to migrate to latest versions of Spring, which prevents other pieces from being updated, due to this dependency as we are unable to move to Hazelcast 5.3.6 without this.
I see there have been no commits in three years, and even dependabot MRs are not even accepeted, so it does look much like a dead project. 😢 

What's the recommended approach?
Shall we look for alternatives?

**Comment by JackPGreen** [comment]
@Verdoso you may be interested in checking out [v5.0](https://github.com/hazelcast/hazelcast-wm/releases/tag/v5.0)!

**Comment by Verdoso** [comment]
I appreciate it, but we had to move on and do it differently without this library, or may be it is integrated now and one does not have to declare it explicitely.
Cheers.
