### ISSUE TITLE
Add sesssion cookie path override

### ISSUE THREAD

**Issue by nilskp** [hazelcast/hazelcast-wm#17]
When using multiple contexts in a web container, a session cookie will always have a Path of the context it's created in. This makes it impossible to have container wide sessions, where the path should be `/`.

There should be some setting to allow for this, either as a boolean override, to use root, or to allow setting a specific path.

**Comment by mesutcelik** [comment]
fixed via https://github.com/hazelcast/hazelcast-wm/pull/26
