### ISSUE TITLE
Depend on Hazelcast 3.7 (instead of 3.7-EA)

### ISSUE THREAD

**Issue by HeXetic** [hazelcast/hazelcast-wm#19]
Now that Hazelcast 3.7 has been released, the pom.xml should be updated to depend on Hazelcast 3.7 instead of 3.7-EA.

**Comment by bilalyasar** [comment]
closed via https://github.com/hazelcast/hazelcast-wm/commit/b5490712e6a80075ba7210cc724b9237c03b69c9
