### ISSUE TITLE
Config object or new Hazelcast instance should not be created when instance-name is specified

### ISSUE THREAD

**Issue by emre-aydin** [hazelcast/hazelcast-wm#28]

**Comment by mesutcelik** [comment]
What happens if `hazelcast-wm` and `hazelcast-hibernate` both defines an instance-name and expect to use the same Hazelcast Instance? Who is going to create Hazelcast Instance?

I might want to have an web app which uses Session Replication and H2LC with one Hazelcast Instance and expect those modules to create or share the same Hazelcast Instance.

**Comment by gAmUssA** [comment]
> What happens if hazelcast-wm and hazelcast-hibernate both defines an instance-name and expect to use the same Hazelcast Instance? Who is going to create Hazelcast Instance?

we need to mention this in our docs that Hazelcast instance, in this case, needs to be created externally (using Spring or in `javax.Servlet.ServletContextListener`)

> I might want to have a web app which uses Session Replication and H2LC with one Hazelcast Instance and expect those modules to create or share the same Hazelcast Instance.

This is the very valid point. Who's going to create Hazelcast instance then?

For the discussion sake, let me complicate things a bit.
What if an application wants to use H2LC, WebSession Replication and Spring's `@EnableCaching` / Spring Caching. SpringCacheManager requires `HazelcastInstance`.

**Comment by gAmUssA** [comment]
Also, I couldn't find a way to "inject" existing `HazelcastInstance` into `ClusteredSessionService`. 
How I can programmatically configure WebFilter with existing `HazelcastInstance`.
Use case - Spring Configuration. I use `HazelcastConfiguration` to create the instance (member or client) and want to pass it to WebFilter.

**Comment by emre-aydin** [comment]
@gAmUssA We had the same question about Hibernate 5 with Spring, as Hibernate 5 no longer allowed to set `RegionFactory` directly. You'll need to configure Hazelcast with an instance name on Spring and pass that name to `WebFilter`.

**Comment by gAmUssA** [comment]
ok, in this case, flow quite obvious
- check if there is an instance with this name `Hazelcast.getInstanceByName()` and return this instance
- otherwise use a `name` parameter to create Hazelcast instance (member or client) same was as we do now.
