### ISSUE TITLE
Replication requires session attributes

### ISSUE THREAD

**Issue by anton-johansson** [hazelcast/hazelcast-wm#29]
Not sure this is an issue or not, but I noticed that session replication does not actually happen if you don't add something to the session.

This means, if you're not using sticky sessions, you'll get a new session ID on every request. This seems a little strange to me, but maybe it's not an issue?

**Comment by emre-aydin** [comment]
Hi @anton-johansson 
This is expected as the plugin hooks to attribute related methods of `javax.servlet.http.HttpSession`. Without adding anything to the session, plugin has no use. Does this cause any problems for you?

**Comment by anton-johansson** [comment]
Well, my application does put something in the session directly, so as soon as I started doing that, it was no issue for me.

But not all applications do put something in the session directly, and if you don't have sticky sessions it feels strange that you'd get a new session ID on every request. But if it is expected, just close the issue! :) I guess it's more value in keeping redundant objects away from Hazelcast though.
