### ISSUE TITLE
Show serialization errors

### ISSUE THREAD

**Issue by T3rm1** [hazelcast/hazelcast-wm#34]
If something to be serialized throws an exception because it is not serializable then this exception is swallowed up and nothing is logged.

If this happens there should be some output to the log.

See the catch block in com.hazelcast.web.HazelcastHttpSession.setAttribute(String, Object)

**Comment by emre-aydin** [comment]
Hi @T3rm1,
Thanks for the feedback. You're right - we should definitely log the exception. Feel free to add it and submit a PR.

**Comment by T3rm1** [comment]
I created #35
