### ISSUE TITLE
HttpServletRequest#getSession(false) still returns a session after #14

### ISSUE THREAD

**Issue by philip-clarke** [hazelcast/hazelcast-wm#39]
Hi,

I have been testing with hazelcast-wm 3.7.1 (via hazelcast 3.8-SNAPSHOT) and found a condition where getSession(false) returns a session even though #14 should be fixed.

To reproduce:
- user logs in via username/password to a web application using spring security and hazelcast
- user makes an api call (which is going to take a long time to return)
- while the 1st api call is ongoing, the user logs out.  This request is handled in a new thread
- From the logs I can see "Published destroy session event"
- Now the first API call finishes and we hit the method saveContext in HttpSessionSecurityContextRepository::SaveToSessionResponseWrapper

In this code we call:
httpSession = request.getSession(false);

which recreates the session and now because we have a session then further down in the code we do:
httpSession.setAttribute(springSecurityContextKey, context);

which saves the thread local context with a fully populated Authentication object into the session.
Now the user is effectively logged back in without having to supply a username/password.

I managed to reproduce this and fix it with the following change in WebFilter:
```
@@ -442,7 +445,11 @@ public class WebFilter implements Filter {

         @Override
         public HazelcastHttpSession getSession(final boolean create) {
+
             hazelcastSession = readSessionFromLocal();
+            if (create == false) {
+                return hazelcastSession;
+            }
             String hazelcastSessionId = findHazelcastSessionIdFromRequest();
             if (hazelcastSession == null && !res.isCommitted() && (create || hazelcastSessionId != null)) {
                 hazelcastSession = createNewSession(HazelcastRequestWrapper.this, hazelcastSessionId);

```

However this was only a quick test just to prove to myself that honouring the create flag would be sufficient.  There could well be other side effects I have not considered.

Please let me know if i can help with logs or reproducing,

Thanks
Philip

**Comment by gokhansari** [comment]
I've also exactly same problem. And it makes me worry about prdocution environment. Is that workaround trustable?

**Comment by gokhansari** [comment]
By the way, even It returns newly created session. isNew() returns false.

**Comment by MattNohelty** [comment]
We are running into the same issue. +1

**Comment by emre-aydin** [comment]
Hi @philip-clarke @gokhansari and @MattNohelty 

Thanks for the detailed report. I think I understand your problem and I have created a pull request that addresses it [here](https://github.com/hazelcast/hazelcast-wm/pull/41) Can you try this and let me know if it solves your problem?

**Comment by emre-aydin** [comment]
@philip-clarke @gokhansari @MattNohelty ,

Did you have a chance to try out the fix I have made [here](https://github.com/hazelcast/hazelcast-wm/pull/41)?

**Comment by MattNohelty** [comment]
@emre-aydin - Is there an easy way to build the hazelcast-all jar from this pull request?

**Comment by emre-aydin** [comment]
@MattNohelty, you can checkout the code from my pull request and change [the version on pom.xml](https://github.com/hazelcast/hazelcast-wm/blob/master/pom.xml#L21) to something like `3.8-custom`, then do a `mvn clean install -DskipTests` to install it into your local Maven repository. Then you can checkout [the main Hazelcast repository](https://github.com/hazelcast/hazelcast) and update [this line](https://github.com/hazelcast/hazelcast/blob/82526527da60603447758b8700497b52aa80a6d7/hazelcast-all/pom.xml#L174-L174) to use `3.8-custom` version you had just created. Doing a `mvn clean install -DskipTests` on the directory you've checkout out Hazelcast will create a `hazelcast-all-3.9-SNAPSHOT.jar` for you with the changes on my pull request.

**Comment by emre-aydin** [comment]
@MattNohelty were you able to try the PR? If you couldn't create the custom hazelcast-all.jar, I can create one for you?

**Comment by MattNohelty** [comment]
@emre-aydin - I was able to test your fix out tonight and I am no longer seeing sessions created when calling HttpServletRequest.getSession(false).  Looks good.

**Comment by emre-aydin** [comment]
@MattNohelty good to know, will merge the changes in.

**Comment by MattNohelty** [comment]
Thanks @emre-aydin!
