### ISSUE TITLE
Option to override WebFilter doFilter

### ISSUE THREAD

**Issue by shaktitripathy** [hazelcast/hazelcast-wm#40]
I am using HazelcastSession with Spring for my web application. I have a health check url which I want to be STATELESS. Since the health check url is hit every 2 secs by load balancer, I see many Hazelcast sessions get opened in the process. That's why I want to make the health check service stateless. While spring security configuration provide me option to make a specific url STATELESS, but Hazelcast WebFilter is creating the session since it sits before the Spring Security Filter.

Would request to provide a solution. I can think of the following.
1. Change in WebFilter to respect spring security STATELESS config
2. remove final identifier letting us override WebFilter doFilter to ignore urls of our choice

**Comment by emre-aydin** [comment]
If calling `request.getSession()` with a `false` argument is an option for you, you can try that.
Until recently, it didn't matter whether you have passed `true` or `false` to `getSession` method, the session was always created. Starting from version 3.7.1, session is only created if you call `getSession` without any arguments or with a `true` argument.

If you step through your code and find where the session is getting created (via `getSession()` or `getSession(true)`), you can change it to `getSession(false)`. If that is not possible (i.e. code you don't own calls it), we can discuss adding an option to `WebFilter` for excluding certain URL patterns from the filter.

**Comment by shaktitripathy** [comment]
Thanks Emre for your quick response. Your hint worked for me. We had a Locale change interceptor which was setting up locale pref and in turn was calling getSession(). Since I didn't want any locale to be set for the health check url, I bypassed the interceptor. So no session is getting created now.

I think we can close the issue.

**Comment by mesutcelik** [comment]
glad to hear that worked for you @shaktitripathy !
I am closing the issue.
