### ISSUE TITLE
Setting hazelcast logging type results in inconsistent logging

### ISSUE THREAD

**Issue by T3rm1** [hazelcast/hazelcast-wm#42]
`hazelcast.logging.type` is supposed to configure the logging framework. This does not work as intended.

The code in `com.hazelcast.web.WebFilter` is executed before the config file is read. This means that the static logger factory field is set to the `StandardLoggerFactory` because the type is null at that time. This results in every log call to `WebFilter.LOGGER` (for example in `com.hazelcast.web.HazelcastHttpSession`) to log to standard out.

Only the code using the LoggingService is using the configured logger factory.

A workaround is to set the logging type as a VM argument.

**Comment by emre-aydin** [comment]
Hi @T3rm1,

How do you configure logging? Do you mean that the logging configuration you've made in your `hazelcast.xml` file is not getting used by `WebFilter`? Maybe we can have a separate configuration parameter for  `WebFilter` but first I want to understand your issue.

**Comment by T3rm1** [comment]
Logging is configured in hazelcast.xml. As mentioned above this config file is read much later than the first call to `WebFilter`. When this happens a static field is set. Since no configuration is yet available the field is set to `StandardLoggerFactory`. The value is never changed after that.

WebFilter shouldn't have a separate configuration for logging. I'm not sure if it is possible to use the LoggingService but if you use that, then this should be the right way.

**Comment by emre-aydin** [comment]
@T3rm1 I think setting the logging type as a VM argument is the way to go here. Lifecycle of the Hazelcast instance (or Hazelcast client instance) and `WebFilter` are different. There are places where we log before any Hazelcast instance is created, so even though we change the code to use `LoggingService` whenever there's a Hazelcast instance, it will never be used by all log statements.

I will add a section about configuring logging and add a warning about this as well. Is there anything that would prevent you from using a VM argument to overcome this problem? If so we might try to find another solution for it.

**Comment by emre-aydin** [comment]
Closing the issue as we didn't hear back from you. Feel free to reopen.

**Comment by T3rm1** [comment]
That's not a problem but it is very inconsistent since you have to declare the same variable twice. I don't understand why you have to log something before logging is set up correctly. This sounds wrong. How does Hazelcast handle this in general? I'm pretty sure there is something that gets logged as well before an instance is created. I haven't looked for it though.

**Comment by emre-aydin** [comment]
> I don't understand why you have to log something before logging is set up correctly.
It's because of the decision to use Hazelcast's logging mechanism. As a module, `hazelcast-wm` does not have a separate logging mechanism but it has a separate lifecycle, i.e. it starts and does things **before** a Hazelcast instance starts (hence Hazelcast logging config takes effect). As we have a workaround in this case, I'm closing the issue.
