### ISSUE TITLE
Allow WebFilter configuration parameters to be set in both FilterConfig and properties

### ISSUE THREAD

**Issue by kulchytskyy** [hazelcast/hazelcast-wm#46]
It is convenient to configure `WebFilter` in both web.xml
```java 
   <init-param>
      <param-name>sticky-session</param-name>
      <param-value>false</param-value>
   </init-param>
   <init-param>
      <param-name>cookie-name</param-name>
      <param-value>hazelcast.sessionId</param-value>
   </init-param>
```
and Spring bean
```java
  <bean id="sessionsReplicationFilter" class="com.hazelcast.web.spring.SpringAwareWebFilter">
    <constructor-arg index="0">
      <props>
        <prop key="config-location">${session.hazelcast.config}</prop>
      </props>
    </constructor-arg>
  </bean>
```
Recently I upgraded hazelcast-wm from 3.7.1 to 3.8 and discovered that parameters from web.xml are ignored. Quick investigation shows that `getValue`-method https://github.com/hazelcast/hazelcast-wm/blob/master/src/main/java/com/hazelcast/web/WebFilterConfig.java#L254 missing `containsKey`-check that we had early in https://github.com/hazelcast/hazelcast-wm/commit/ff07d0351ace7ca07217d1824bc81e0ee7b5164c#diff-f623257421f1eeeee37dadb8a93459c2L397
Are any reasons to skip filter parameters if properties were initialized or it was just missed during refactoring?

**Comment by emre-aydin** [comment]
Nice catch @kulchytskyy ! Thanks for reporting it. I've just sent a PR for fixing it. Indeed it was missed during refactoring.
