### ISSUE TITLE
possible data-loss using sticky-session=true / compatibility enhancement

### ISSUE THREAD

**Issue by dfex55** [hazelcast/hazelcast-wm#50]
Current implementation of sticky-sessions requires the load-balancer (lb) to stick to a node after a failover. However, there are some edge-cases which might lead to data-loss and incompatibilities with some lbs.

**Example:**

1. lb routes user1 to node1
2. user1 writes "data1" for key "test" into session
3. node1 becomes unreachable
4. lb re-routes user1 to node2
5. user1 writes "data2" for key "test" into session
6. node1 becomes reachable again - was not restarted

**A - lb provides required stickyness:**
7. node2 becomes unreachable
8. lb re-routes user1 to node1
9. data2 from 5. is lost

**B - different behavior of lb e.g. nginx:**
7. lb instantly re-routes user1 back to original node1
8. data2 from 5. is lost

**What happens:**
- After the first failover (4.) session data will be available on node2 because hazelcast fetches the session from the map (creates a new local HazelcastHttpSession).
- After the second "failover" in A.8 or different lb behavior in B.7, a local HazelcastHttpSession already exists and no data is fetched from the map
- The value for key "test" is "data1" again -> "data2" is lost

**Proposal:**
- remove entries and/or set reload flag on all other nodes, when a node must create a new sticky HazelcastHttpSession (once)

This would make HazelcastHttpSession compatible with nginx upstream configuration and eliminates rare edge cases, in which a node was temporarily unavailable and previously routed users are re-routed back.

**Comment by emre-aydin** [comment]
I understand the problem you're describing but your solution proposal defeats the whole purpose of 'sticky' concept in `hazelcast-wm`. To avoid the problem you describe, one can set "sticky=false" and be done with it. 

It is impossible to detect this situation as the node that is unreachable for a short amount of time has no way of knowing it was unreachable (or I cannot think of a way), so it cannot take any actions such as removing the entries. 

The only solution I can think of is having last updated timestamps on each entry and checking whether the data in cluster is more up to date, but again this will also defeat the purpose of having sticky and a local cache (which is avoiding fetching session attributes over network from the cluster). I would love to hear your thoughts on these and hear any possible solutions. Feel free to implement your solution and submit a PR. I think a test that shows this situation would be a good start.

**Comment by emre-aydin** [comment]
@dfex55 I'm closing this one as we haven't heard back from you in a while. Feel free to reopen it if you have any updates.
