### ISSUE TITLE
Synchronization problems with hazelcast master branch

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [hazelcast/hazelcast-wm#7]
Synchronization problems with hazelcast master branch

## Problem1

I want to use hazelcast.jar・hazelcast-client.jar・hazelcast-wm.jar build from master branch.
But, hazelcast-wm.jar build from master branch is not compatible with hazelcast.jar・hazelcast-client.jar build from master branch.

```java
com.hazelcast.spi.impl.SerializationServiceSupport.getSerializationService()Lcom/hazelcast/internal/serialization/SerializationService;
java.lang.NoSuchMethodError: com.hazelcast.spi.impl.SerializationServiceSupport.getSerializationService()Lcom/hazelcast/internal/serialization/SerializationService;
at com.hazelcast.web.ClusteredSessionService.setAttribute(ClusteredSessionService.java:235) ~[hazelcast-wm-3.7-SNAPSHOT.jar:3.7-SNAPSHOT]
```

* Cause

Because the interface of hazelcast.jar has been changed by the following commit.
https://github.com/hazelcast/hazelcast/commit/be54c26babf192d79b42973e6e9a46ba3a725d69

com.hazelcast.internal.serialization.SerializationService
↓
com.hazelcast.spi.serialization.SerializationService

## Problem2

I want to make pull request that fix Problem1, but hazelcast-wm master branch cannot refer hazelcast-3.7-SNAPSHOT.jar.
Because hazelcast-wm master branch pom.xml's default hazelcast.version is not 3.7-SNAPSHOT but 3.6.

Can I update default hazelcast.version to 3.7-SNAPSHOT?

Even now,master profile's hazelcast.version(hazelcast-wm master branch pom.xml) is 3.7-SNAPSHOT.
Therefore, compile error occurs when I build by 'mvn install -P master'.

```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project hazelcast-wm: Compilation failure: Compilation failure:
[ERROR] /Users/yoshimoto/git/hazelcast-wm/src/main/java/com/hazelcast/web/ClusteredSessionService.java:[22,43] エラー: シンボルを見つけられません
[ERROR] シンボル:   クラス SerializationService
[ERROR] 場所: パッケージ com.hazelcast.internal.serialization
[ERROR] /Users/yoshimoto/git/hazelcast-wm/src/main/java/com/hazelcast/web/ClusteredSessionService.java:[282,8] エラー: シンボルを見つけられません
[ERROR] -> [Help 1]
```

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-wm/pull/9

**Comment by daisuke-yoshimoto** [comment]
@bilalyasar @mesutcelik 
Thank you for fix.
