### ISSUE TITLE
HazelcastInstanceLoader ignores instance-name for clients

### ISSUE THREAD

**Issue by nilskp** [hazelcast/hazelcast-wm#8]
The `instance-name` init param is ignored for client instances.

**Comment by pveentjer** [comment]
Where does HazelcastInstanceLoader come from? I don't see it in the 3.7 source.

**Comment by nilskp** [comment]
https://github.com/hazelcast/hazelcast-wm/blob/master/src/main/java/com/hazelcast/web/HazelcastInstanceLoader.java#L63

Instance name (L66) is not used when client (L83), but is when member (L86).
